server:
  port: 1996
spring:
  application:
    name: first-microservice
  zipkin:
    base-url: http://localhost:9411  # Zipkin Server URL
    tracing:
      sampling:
        probability: 1.0  # 100% tracing for all requests

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true

# Enable actuators
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  tracing:
    sampling:
      probability: 1.0  # 100% tracing (adjust for production)
    zipkin:
      tracing.endpoint: http://localhost:9411/api/v2/spans  # Zipkin endpoint
